Intro to Proportional control
Open-STEM/IntroToRoboticsV2 pull request #123
Opened 2023-08-20 01:48 UTC by AnselChang

2023-08-20 03:14 UTC, Kreeevin approved these changes

2023-08-20 03:14 UTC, Kreeevin commented on course/robot_control/intro_to_prop_control.rst
> +Imagine you're driving a car and you want to keep at a steady speed. If you're going too slow,
Will need to replace this analogy down the line

2023-08-21 02:53 UTC, Kreeevin requested changes
You're really testing the boundaries of 'acceptable' with this, but I admire your boldness.

2023-08-21 02:53 UTC, Kreeevin commented on course/robot_control/prop_distance_tracker.rst
> +to the distance error. As a reminder for P control, this will be calculated as :code:`motorEffort = Kp * error`.
why the change to camel case here? I notice the blockly also uses it, but I thought we were sticking to python snake_case whenever possible?

2023-08-21 02:53 UTC, Kreeevin commented on course/robot_control/prop_distance_tracker.rst
> +    #. Poll the rangefinder to get the current distance
Use of the word Poll is a small nitpick, but may not make sense to non-stem/robotics people

2023-08-21 02:53 UTC, Kreeevin commented on course/robot_control/prop_distance_tracker.rst
> +to the distance error. As a reminder for P control, this will be calculated as :code:`motorEffort = Kp * error`.
this actually applied to everywhere in the section. What is being done elsewhere in the curriculum?

2023-08-21 03:02 UTC, AnselChang commented on course/robot_control/prop_distance_tracker.rst
> +    #. Poll the rangefinder to get the current distance
fixed

2023-08-21 03:02 UTC, AnselChang commented on course/robot_control/prop_distance_tracker.rst
> +to the distance error. As a reminder for P control, this will be calculated as :code:`motorEffort = Kp * error`.
fixed

2023-08-21 03:05 UTC, Kreeevin approved these changes
Wow! Your work is absolutely amazing! It's like a synchronization rate off the charts, just pure excellence! You've really piloted this project to greatness and left the Angels in awe. Keep it up, and you'll be the Eva pilot of success!

2023-08-21 03:05 UTC, merged